services:
  app:
    container_name: pladonf_discord_bot
    environment:
      - TOKEN=$TOKEN
      - KEYCLOAK_REALM=$KEYCLOAK_REALM
      - KEYCLOAK_CLIENT_NAME=$KEYCLOAK_CLIENT_NAME
      - KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4300:4300
    networks:
      - pladonf_api
      - pladonf_auth
networks:
  pladonf_api:
    external: true
  pladonf_auth:
    external: true